version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
   
    commands:
        # install npm
        - npm install
       
  build:
    commands:
        # run build script
        - REACT_APP_URL=$URL npm run build
        - aws s3 cp --recursive build/ $S3_URI